STORE = "data.json"

[COMMANDS]
CALC_WEIGHTS = "calc_weights"
ONE_RM = "one_rm"

[DATA]
TOTAL_WEIGHT = "total_weight"
BAR_WEIGHT = "bar_weight"
WEIGHT_UNIT = "weight_unit"

[DEFAULT]
TOTAL_WEIGHT = 0
BAR_WEIGHT = 45
WEIGHT_UNIT = "Lb"

